### ISSUE TITLE
Uppsättning API: Orders

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Orders-RIKA-WIN23#3]
**Tasks:**
- [x]  Skapa GitHub-repo
- [ ]  Sätt upp projekt inklusive mappstruktur
- [x] Skapa main branch
- [x] Skapa dev branch
